# TITULO: DESPLIEGUE AUTOMÁTICO EN GITHUB PAGES (HTML ESTÁTICO)
name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

# Permisos necesarios para que GitHub Actions pueda publicar la web
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Indicamos que suba la raíz del proyecto (donde están index.html, style.css y script.js)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
